sudo: required
services:
  - docker

before_install:
  - docker build -t ricky37d/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ricky37d/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-369559648783"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: "$AWS_BEANSTALK_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_BEANSTALK_SECRET_KEY"
